#! /bin/sh

#autostart
~/.config/scripts/bspwm/autostart.sh &

# This prevents from loading multiple times the same options on reload
bspc rule -r "*"

# for scratchpad
# bspc wm -a PAD 1920x1080+3840+0

#monitors
bspc monitor DP-1 -n laptop
bspc monitor HDMI-1 -n HDMI
bspc monitor -d 1 2 3 4 5 6
bspc monitor PAD -d Xpad

bspc config border_width         1
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod4

#mouse
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config ignore_ewmh_focus true # then move window don't focus

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
bspc desktop 1 --layout monocle
bspc desktop 2 --layout monocle
bspc desktop 3 --layout monocle
bspc desktop 5 --layout floating

#
bspc rule -a "*:*:Picture in Picture" state=floating
bspc rule -a "discord" state=floating
bspc rule -a "TelegramDesktop" state=floating

bspc rule -a ./ layer=normal
bspc rule -a firefox -o desktop='Xpad' follow=off state=floating center=on rectangle=1200x700+0+0
bspc rule -a "Google-chrome" -o desktop=^1 follow=off 
bspc rule -a "Code" -o desktop=^2 follow=off
# bspc rule -a Thunderbird -o desktop='Xpad' follow=off state=floating center=on rectangle=1200x900+0+0

# for java apps
wmname LG3D